# Generated by Django 6.0.4 on 2026-06-11 06:07

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='ARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Area de Resultado Clave',
                'verbose_name_plural': 'Areas de Resultados Clave',
                'db_table': 'arc',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Lineamiento',
                'verbose_name_plural': 'Lineamientos',
                'db_table': 'lineamiento',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200, verbose_name='Nombre a mostrar')),
                ('email', models.EmailField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Inhabilitado')),
                ('date_last_login', models.DateField(blank=True, null=True)),
                ('time_last_login', models.TimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='core_users', to='auth.group')),
                ('plan_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprueba plan')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('parent', models.ForeignKey(blank=True, db_column='id_uo_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organizationalunit', verbose_name='Unidad Padre')),
                ('responsible', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Unidad Organizativa',
                'verbose_name_plural': 'Unidades Organizativas',
                'db_table': 'unidad_organizativa',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='idrol', on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'user_rol',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='core.UserRole', to='core.role'),
        ),
        migrations.CreateModel(
            name='WorkObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('arc', models.ForeignKey(blank=True, db_column='id_arc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arc', verbose_name='ARC')),
            ],
            options={
                'verbose_name': 'Objetivo de Trabajo',
                'verbose_name_plural': 'Objetivos de Trabajo',
                'db_table': 'objetivo_trabajo',
            },
        ),
        migrations.CreateModel(
            name='MeasurementCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('objective', models.ForeignKey(blank=True, db_column='id_objetivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workobjective', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Criterio de Medida',
                'verbose_name_plural': 'Criterios de Medida',
                'db_table': 'criterio_medida',
            },
        ),
    ]
