# Generated by Django 6.0.4 on 2026-06-11 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(max_length=50, verbose_name='Tipo Permiso')),
                ('object_type', models.CharField(max_length=100, verbose_name='Tipo Objeto')),
                ('object_id', models.IntegerField(verbose_name='ID Objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso por Objeto',
                'verbose_name_plural': 'Permisos por Objeto',
                'db_table': 'permiso_objeto',
                'unique_together': {('user', 'permission_type', 'object_type', 'object_id')},
            },
        ),
    ]
