# Generated by Django 6.0.4 on 2026-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objectpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.IntegerField(default=25)),
                ('use_tls', models.BooleanField(default=False)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('default_from', models.EmailField(default='noreply@example.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración Email',
                'verbose_name_plural': 'Configuración Email',
                'db_table': 'configuracion_email',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración Sistema',
                'verbose_name_plural': 'Configuraciones Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
