# Generated by Django 6.0.6 on 2026-06-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailconfig_systemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Actividad', 'verbose_name_plural': 'Tipos de Actividad'},
        ),
        migrations.AlterModelOptions(
            name='arc',
            options={'ordering': ['number'], 'verbose_name': 'Area de Resultado Clave', 'verbose_name_plural': 'Areas de Resultados Clave'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='guideline',
            options={'ordering': ['name'], 'verbose_name': 'Lineamiento', 'verbose_name_plural': 'Lineamientos'},
        ),
        migrations.AlterModelOptions(
            name='measurementcriterion',
            options={'ordering': ['name'], 'verbose_name': 'Criterio de Medida', 'verbose_name_plural': 'Criterios de Medida'},
        ),
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'ordering': ['parent_id', 'sort_order', 'name'], 'verbose_name': 'Unidad Organizativa', 'verbose_name_plural': 'Unidades Organizativas'},
        ),
        migrations.AlterModelOptions(
            name='workobjective',
            options={'ordering': ['name'], 'verbose_name': 'Objetivo de Trabajo', 'verbose_name_plural': 'Objetivos de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='emailconfig',
            name='password',
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='_password',
            field=models.CharField(blank=True, db_column='password', max_length=255, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='organizationalunit',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
