# Generated by Django 6.0.6 on 2026-07-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_uo_sort_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectPermission',
        ),
    ]
