# Generated by Django 6.0.4 on 2026-07-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'ordering': ['id'], 'verbose_name': 'Configuración Email', 'verbose_name_plural': 'Configuración Email'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key'], 'verbose_name': 'Configuración Sistema', 'verbose_name_plural': 'Configuraciones Sistema'},
        ),
    ]
