# Generated by Django 6.0.4 on 2026-06-11 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Fin')),
                ('is_extraplan', models.BooleanField(default=False, verbose_name='Extraplan')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('observation', models.CharField(blank=True, max_length=600, null=True, verbose_name='Observacion')),
                ('start_time', models.TimeField(verbose_name='Hora Plan')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('has_incidence', models.BooleanField(default=False, verbose_name='Incidencia')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('is_modified', models.BooleanField(default=False, verbose_name='Modificado')),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_periods', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Periodo de Cronograma',
                'verbose_name_plural': 'Periodos de Cronograma',
                'db_table': 'cronograma_periodo',
                'unique_together': {('activity', 'start_date', 'end_date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='Fecha del Plan')),
                ('approved_date', models.DateField(verbose_name='Fecha Aprobado')),
                ('organizational_unit', models.ForeignKey(db_column='id_unidad_organizativa', on_delete=django.db.models.deletion.CASCADE, to='core.organizationalunit')),
            ],
            options={
                'verbose_name': 'Plan Aprobado',
                'verbose_name_plural': 'Planes Aprobados',
                'db_table': 'plan_aprobado',
                'unique_together': {('organizational_unit', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleOrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado')),
                ('organizational_unit', models.ForeignKey(db_column='id_unidad_organizativa', on_delete=django.db.models.deletion.CASCADE, to='core.organizationalunit')),
                ('schedule_period', models.ForeignKey(db_column='id_cronograma', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleperiod')),
            ],
            options={
                'verbose_name': 'Cronograma por UO',
                'verbose_name_plural': 'Cronogramas por UO',
                'db_table': 'cronoperiodo_uo',
                'unique_together': {('schedule_period', 'organizational_unit')},
            },
        ),
        migrations.CreateModel(
            name='SchedulePeriodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_period', models.ForeignKey(db_column='id_cronograma_periodo', on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleperiod')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periodo de Cronograma Mapeado',
                'verbose_name_plural': 'Periodos de Cronograma Mapeados',
                'db_table': 'cronograma_periodo_mapeado',
                'unique_together': {('schedule_period', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Dia')),
                ('user', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dia Laborable',
                'verbose_name_plural': 'Dias Laborables',
                'db_table': 'dialaborable',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
