# Generated by Django 6.0.4 on 2026-06-11 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_period', models.ForeignKey(db_column='id_cronograma_periodo', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='schedule.scheduleperiod')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Cronograma',
                'verbose_name_plural': 'Comentarios de Cronogramas',
                'db_table': 'cronograma_comentario',
            },
        ),
    ]
