# Generated by Django 6.0.4 on 2026-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_actividad_descrip_4b2a72_idx_and_more'),
        ('core', '0003_emailconfig_systemconfig'),
        ('schedule', '0002_schedulecomment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduleorgunit',
            index=models.Index(fields=['status'], name='cronoperiod_status_a0e766_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleperiod',
            index=models.Index(fields=['start_date'], name='cronograma__start_d_abbe24_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleperiod',
            index=models.Index(fields=['end_date'], name='cronograma__end_dat_2059a8_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleperiod',
            index=models.Index(fields=['status'], name='cronograma__status_956786_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleperiod',
            index=models.Index(fields=['activity'], name='cronograma__id_acti_e88aa1_idx'),
        ),
    ]
