# Generated by Django 6.0.4 on 2026-06-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduleorgunit_cronoperiod_status_a0e766_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleperiod',
            options={'ordering': ['start_date'], 'verbose_name': 'Periodo de Cronograma', 'verbose_name_plural': 'Periodos de Cronograma'},
        ),
        migrations.AlterModelOptions(
            name='workday',
            options={'ordering': ['day'], 'verbose_name': 'Dia Laborable', 'verbose_name_plural': 'Dias Laborables'},
        ),
    ]
