# Generated by Django 6.0.4 on 2026-07-15 23:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activityparticipant_activity_participant_users_and_more'),
        ('core', '0006_seed_roles'),
        ('schedule', '0004_approvedplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvedplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvedplan',
            name='activity',
            field=models.ForeignKey(blank=True, db_column='id_actividad', null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='approvedplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='id_aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por'),
        ),
        migrations.AddField(
            model_name='approvedplan',
            name='end_date',
            field=models.DateField(db_column='fecha_fin', default=datetime.date.today, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='approvedplan',
            name='observations',
            field=models.TextField(blank=True, db_column='observaciones', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='approvedplan',
            name='start_date',
            field=models.DateField(db_column='fecha_inicio', default=datetime.date.today, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='approvedplan',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_aprobacion', verbose_name='Fecha de Aprobación'),
        ),
        migrations.AlterField(
            model_name='approvedplan',
            name='organizational_unit',
            field=models.ForeignKey(db_column='id_unidad_organizativa', on_delete=django.db.models.deletion.CASCADE, to='core.organizationalunit', verbose_name='Unidad Organizativa'),
        ),
        migrations.RemoveField(
            model_name='approvedplan',
            name='plan_date',
        ),
    ]
