# Generated by Django 6.0.4 on 2026-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('modelo', models.CharField(blank=True, max_length=300, null=True)),
                ('accion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'db_table': 'logstore',
            },
        ),
    ]
