# Generated by Django 6.0.4 on 2026-06-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='data_diff',
            field=models.JSONField(blank=True, null=True, verbose_name='Diferencia de Datos'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='accion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
