# Generated by Django 6.0.4 on 2026-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logentry_data_diff_logentry_ip_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['username'], name='logstore_usernam_14e6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['modelo'], name='logstore_modelo_b879d1_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['object_id'], name='logstore_object__e7d82e_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['fecha'], name='logstore_fecha_9dc235_idx'),
        ),
    ]
