# Generated by Django 6.0.4 on 2026-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadatos'),
        ),
    ]
