# Generated by Django 6.0.4 on 2026-06-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar')),
                ('responsible', models.CharField(blank=True, max_length=500, null=True, verbose_name='Responsables')),
                ('participants', models.CharField(blank=True, max_length=500, null=True, verbose_name='Participantes')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('is_general', models.BooleanField(default=False, verbose_name='General')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='ActivityGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Lineamiento de Actividad',
                'verbose_name_plural': 'Lineamientos de Actividades',
                'db_table': 'actividad_lineamiento',
            },
        ),
        migrations.CreateModel(
            name='ActivityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Actividad Mapeada',
                'verbose_name_plural': 'Actividades Mapeadas',
                'db_table': 'actividad_mapeada',
            },
        ),
        migrations.CreateModel(
            name='ActivityOrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Actividad por UO',
                'verbose_name_plural': 'Actividades por UO',
                'db_table': 'actividad_uo',
            },
        ),
    ]
