# Generated by Django 6.0.4 on 2026-06-11 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, db_column='id_tipo_actividad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.activitytype', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='activity',
            name='arc',
            field=models.ForeignKey(blank=True, db_column='id_arc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arc', verbose_name='ARC'),
        ),
        migrations.AddField(
            model_name='activity',
            name='associated_objective',
            field=models.ForeignKey(blank=True, db_column='id_objetivo_asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workobjective', verbose_name='Objetivo Asociado'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='measurement_criterion',
            field=models.ForeignKey(blank=True, db_column='id_criterio_medida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.measurementcriterion', verbose_name='Criterio de Medida'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizational_unit',
            field=models.ForeignKey(blank=True, db_column='id_unidad_organizativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organizationalunit', verbose_name='Unidad Organizativa'),
        ),
        migrations.AddField(
            model_name='activityguideline',
            name='activity',
            field=models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityguideline',
            name='guideline',
            field=models.ForeignKey(db_column='id_lineamiento', on_delete=django.db.models.deletion.CASCADE, to='core.guideline'),
        ),
        migrations.AddField(
            model_name='activitymapping',
            name='activity',
            field=models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activitymapping',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityorgunit',
            name='activity',
            field=models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityorgunit',
            name='organizational_unit',
            field=models.ForeignKey(db_column='id_unidad_organizativa', on_delete=django.db.models.deletion.CASCADE, to='core.organizationalunit'),
        ),
        migrations.AlterUniqueTogether(
            name='activityguideline',
            unique_together={('activity', 'guideline')},
        ),
        migrations.AlterUniqueTogether(
            name='activitymapping',
            unique_together={('activity', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='activityorgunit',
            unique_together={('activity', 'organizational_unit')},
        ),
    ]
