# Generated by Django 6.0.4 on 2026-06-11 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('schedule', '0002_schedulecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='activity_attachments/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='id_subido_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de Actividad',
                'verbose_name_plural': 'Adjuntos de Actividades',
                'db_table': 'actividad_adjunto',
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Actividad',
                'verbose_name_plural': 'Comentarios de Actividades',
                'db_table': 'actividad_comentario',
            },
        ),
        migrations.CreateModel(
            name='UnfulfilledActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='unfulfilled_records', to='activities.activity')),
                ('registered_by', models.ForeignKey(blank=True, db_column='id_registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule_period', models.ForeignKey(blank=True, db_column='id_cronograma_periodo', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleperiod')),
            ],
            options={
                'verbose_name': 'Actividad Incumplida',
                'verbose_name_plural': 'Actividades Incumplidas',
                'db_table': 'actividad_incumplida',
            },
        ),
    ]
