# Generated by Django 6.0.4 on 2026-06-11 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityattachment_activitycomment_and_more'),
        ('core', '0003_emailconfig_systemconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['description'], name='actividad_descrip_4b2a72_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organizational_unit'], name='actividad_id_unid_9be048_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='actividad_id_cate_6ac7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by'], name='actividad_created_e076e1_idx'),
        ),
        migrations.AddIndex(
            model_name='activityorgunit',
            index=models.Index(fields=['status'], name='actividad_u_status_978602_idx'),
        ),
    ]
