# Generated by Django 6.0.6 on 2026-06-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_actividad_descrip_4b2a72_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
    ]
