# Generated by Django 6.0.4 on 2026-07-15 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_responsible_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='participant_relations', to='activities.activity')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de Actividad',
                'verbose_name_plural': 'Participantes de Actividades',
                'db_table': 'actividad_participante',
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='participant_users',
            field=models.ManyToManyField(blank=True, related_name='participant_in_activities', through='activities.ActivityParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participantes (usuarios)'),
        ),
        migrations.CreateModel(
            name='ActivityResponsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='responsible_relations', to='activities.activity')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de Actividad',
                'verbose_name_plural': 'Responsables de Actividades',
                'db_table': 'actividad_responsable',
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, related_name='responsible_in_activities', through='activities.ActivityResponsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsables (usuarios)'),
        ),
    ]
